/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2024-06-13 08:20:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class join_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/Nav.jsp", Long.valueOf(1717406636179L));
    _jspx_dependants.put("/Header.jsp", Long.valueOf(1717390287624L));
    _jspx_dependants.put("/Footer.jsp", Long.valueOf(1717390287625L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    ");

    	if(request.getAttribute("result") != null){
    		int result = (int)request.getAttribute("result");
    		if(result > 0){
    
      out.write("\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("    	alert(\"저장되었습니다.\");\r\n");
      out.write("    </script>\r\n");
      out.write("    ");
	}else{
    
      out.write("\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("    	alert(\"저장이 실패되었습니다.\")\r\n");
      out.write("    </script>\r\n");
      out.write("    ");

    		}
    	}	
    	int custno = (int) request.getAttribute("custno");
    
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./css/style.css\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	function validate(){\r\n");
      out.write("		\r\n");
      out.write("		const phoneRegexp = /^(0)\\d{1,2}-\\d{3,4}-\\d{4}$/;\r\n");
      out.write("		//회원성명 체크\r\n");
      out.write("		if(form.custname.value ===\"\") {\r\n");
      out.write("			alert(\"회원성명을 입력하지 않았습니다.\");\r\n");
      out.write("			form.custname.focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		if(form.phone.value === \"\") {\r\n");
      out.write("			alert(\"전화번호를 입력하지 않았습니다.\");\r\n");
      out.write("			form.phone.focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}else {\r\n");
      out.write("			if(!phoneRegexp.test(form.phone.value)){\r\n");
      out.write("				alert(\"전화번호 형식으로 입력하세요\");\r\n");
      out.write("				form.phone.focus();\r\n");
      out.write("				return false;\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("		//주소\r\n");
      out.write("		if(form.address.value===\"\") {\r\n");
      out.write("			alert(\"주소를 입력하지 않았습니다.\");\r\n");
      out.write("			form.address.focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		//가입일 체크\r\n");
      out.write("		if(form.joindate.value===\"\") {\r\n");
      out.write("			alert(\"가입일자를 입력하지 않았습니다.\");\r\n");
      out.write("			form.joindate.focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		if(form.grade.value===\"\"){\r\n");
      out.write("			alert(\"고객등급을 입력하지 않았습니다.\");\r\n");
      out.write("			form.grade.focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}else {\r\n");
      out.write("			if(!(form.grade.value===\"A\"|| form.grade.value===\"B\" || form.grade.value===\"C\")) {\r\n");
      out.write("				alert(\"고객등급을 정확히 입력하세요.\");\r\n");
      out.write("				form.grade.focus();\r\n");
      out.write("				return false;\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("			\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./css/style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<header class=\"header\">\r\n");
      out.write("		쇼핑몰 회원관리 ver1.0\r\n");
      out.write("	</header>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./css/style.css\"/>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<nav class=\"nav\">\r\n");
      out.write("		<ul>\r\n");
      out.write("			<li><a href=\"Register\">회원등록</a></li>\r\n");
      out.write("			<li><a href=\"GetMember\">회원목록 조회/수정</a></li>\r\n");
      out.write("			<li><a href=\"Money\">회원매출 조회</a></li>\r\n");
      out.write("			<li><a href=\"\">홈쇼핑 회원 정보 수정</a></li>\r\n");
      out.write("		</ul>\r\n");
      out.write("	</nav>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("		<br/>\r\n");
      out.write("	<section class=\"section\">\r\n");
      out.write("		<div align=\"center\" style=\"margin: 0 auto;\">\r\n");
      out.write("			<h3>홈쇼핑 회원 등록</h3>\r\n");
      out.write("		</div>\r\n");
      out.write("		<br/>\r\n");
      out.write("		<div align=\"center\">\r\n");
      out.write("			<form name=\"form\" action=\"RegisterCtrl\" method=\"post\" onsubmit=\"return validate();\">\r\n");
      out.write("				<input name=\"action\" type=\"hidden\" value=\"join\">\r\n");
      out.write("				<table style=\"width: 400px;\">\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th>회원번호(자동생성)</th>\r\n");
      out.write("						<td>\r\n");
      out.write("							<input name=\"custno\" type=\"text\" value=\"");
      out.print(custno);
      out.write("\" disabled>\r\n");
      out.write("						</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th>회원성명</th>\r\n");
      out.write("						<td>\r\n");
      out.write("							<input type=\"text\" name=\"custname\">\r\n");
      out.write("						</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th>회원전화</th>\r\n");
      out.write("						<td>\r\n");
      out.write("							<input type=\"text\" name=\"phone\">\r\n");
      out.write("						</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th>회원주소</th>\r\n");
      out.write("						<td>\r\n");
      out.write("							<input type=\"text\" name=\"address\">\r\n");
      out.write("						</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th>가입일자</th>\r\n");
      out.write("						<td>\r\n");
      out.write("							<input type=\"date\" name=\"joindate\">\r\n");
      out.write("						</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th>고객등급[A: VIP, B:일반, C:직원]</th>\r\n");
      out.write("						<td>\r\n");
      out.write("							<input type=\"text\">\r\n");
      out.write("						</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th>도시코드</th>\r\n");
      out.write("						<td>\r\n");
      out.write("							<input type=\"text\">\r\n");
      out.write("						</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td colspan=\"2\" align=\"center\">\r\n");
      out.write("							<input type=\"submit\" value=\"등록\"/>\r\n");
      out.write("							<input type=\"button\" onclick=\"location.href='GetMember'\" value=\"조회\">\r\n");
      out.write("						</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("				</table>\r\n");
      out.write("			</form>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./css/style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<footer class=\"footer\">\r\n");
      out.write("		<ul>\r\n");
      out.write("			<li>HRDKorea copyright &copy; 2016 All right reserved. Human Resouces Development Serivce of Korea.</li>\r\n");
      out.write("		</ul>\r\n");
      out.write("	</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
